import Head from "next/head";
import React from "react";

export default function LandingPages() {
  return (
    <>
      <Head>
        <title>Al-Qur&apos;an | Rhein Sullivan</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </>
  );
}
